#!/usr/bin/python3

import data
import heatmap

import os
import json
import sys 

os.chdir(os.path.dirname(os.path.realpath(__file__))) # moves to directory of 

try:
    dic = json.load(open(os.getcwd()+'/stats.json'))
except:
    dic = {"stepno" : 4}

help = """
    list of arguments:

    -e, --e.g.      [args]                  (optional [args])                       description

    -a, --add       [name]                                                          add a new habit (if not already existing).
    -r, --remove    [habit]                                                         remove a habit.
    -t, --track     [habit] [day] [stepno]                                          add or edit a record. (day must be tdy, yst or a date in ISO format (YYYY-MM-DD), stepno has to be a number from 0 - default step number)

    -m, --map       [habit]                 (-s [start]) )(-e [end]) (-n [steps])   view heatmap for habit.

    -h, --help                                                                      see all commands.
    -s, --steps     [number]                                                        set the default number of steps in heatmap (number from 1-4)
                                                                                    (having one step would mean that you either have or have not done the habit but having more steps allows you to indicate anything in between)
    """

comm = """"""

if len(sys.argv) == 1:
    print(help)
else:
    match sys.argv[1]:
        case "-a" | "--add":
            data.add(dic, sys.argv[2])
        case "-h" | "--help":
            print(help)
        case "-m" | "-map":
            pass
        case "-r" | "--remove":
            try:
                del dic[sys.argv[2]]
            except:
                print("not found")
            else:
                print(f"{sys.argv[2]} deleted.")
        case "-t" | "--track":
            data.track(dic, *sys.argv[2:5])

open(os.getcwd()+"/stats.json", "w").write(json.dumps(dic, indent=4))
