#!/usr/bin/python3

import main

import datetime as dt
import os
import json
import toml
import sys 

os.chdir(os.path.dirname(os.path.realpath(__file__)))  

try:
    dic = json.load(open(os.getcwd()+'/stats.json'))
except:
    dic = {}

try:
    sett = toml.load(open(os.getcwd()+'/config.toml'))
except:
    sett = {}

if sett == {}:
    sett["stepno"] = 4
    sett["defcol"] = "#FFFFFF"

defcol = sett["defcol"]

comms = """
    usage: hbmp [command] [argument]
    
    list of arguments:

    command:
    -a, --arg.      [args]                      ([optional] [args])     description
    
    habit:
    -a, --add       [name]                                              add a new habit (if not already existing).
    -r, --remove    [habit]                                             remove a habit.
    -t, --track     [day]                       ([habit] [stepno])      add or edit a record.

    map:
    -l, --list                                                          list all habits.
    -d, --day       [start] [end]               ([color])               view heatmap for all habits from one day to another.
    -m, --month     [start] [end]               ([color])               view heatmap for all habits from the start of a month to the beginning of another.
    -y, --year      [habit] [year]              ([color])               view year heatmap for habit.
    -b, --bydur     [start] [end] [duration]    ([color])               view heatmap based on average of week/month/year

    help:                                                               see all commands and explanations.

    steps:          [number]                                            set the default number of steps in heatmap (number from 1-4)
"""

help = """
    commands:

        habit:

        -a, --add [name]: add a new habit.
        adds a new habit with name [name] to the database.
        
        [name]: any string.

        -r, --remove [name]: removes a habit.
        removes the habit named [name] from the database.

        [name]: any string.

        -l, --list: lists all habits.

        -t, --track [day] ([habit] [stepno]): adds or edits a record.
        adds or edits the record of habit [habit] on [day] (0 by default) and changes it to [stepno].
        if [habit] and [stepno] are left blank, you will be prompted to enter a number for each habit.

        [day]: either "tdy", "yst", or a date in ISO format (YYYY-MM-DD).
        [habit]: name of an existing habit.
        [stepno]: a number from 0 to the default step number

        map:
        
        -d, --day [start] [end] ([color]): view day heatmap for all habits.
        displays a single bar of each habit's data on [day], optionally in [color]
        
        [start], [end]: either "tdy", "yst", or a date in ISO format (YYYY-MM-DD).
        [color]: any hex code (no preceding "#")

        -m, --month [start] [end] ([color]): view day heatmap for all habits over a few months.
        displays a single bar of each habit's data on [day], optionally in [color]
        
        [start], [end]: any month in ISO format (date without day, YYYY-MM).
        [color]: any hex code (no preceding "#")

        -y, --year [habit] [year] ([color]): displays a heatmap.
        displays a calendar heatmap of the data in [habit] for [year], optionally in [color].

        [habit]: name of an existing habit.
        [year]: any valid integer from 1 to 9999 (based on python's datetime module's limits)
        [color]: any hex code (no preceding "#")

        -v, --average [start] [end] [duration]: view heatmap for all habits based on week/month/year.
        [start], [end]: either "tdy", "yst", or a date in ISO format (YYYY-MM-DD).
        [duration]: either "week", "month" or "year"

        misc:

        -h, --help: see this message.

        -s, --steps [number]: sets the default number of steps.
        sets the default number of steps (at the moment, this number of steps applies to all habits)
        having one step would mean that you either have or have not done the habit but having more steps allows you to indicate anything in between.

        [number]: any number from 1-4.

    explaining steps:

        steps are the number of different values enterable for each record. if a habit only has the option to be marked as done or not done, we count that as one step.
        if a habit has two steps, one would be allowed to mark the habit as done, undone or half-done. similar rules apply for three or four steps.
        the step conversion table is as follows:
        
        og max no. of steps:    in 1-step:      in 2-step:      in 3-step       in 4-step:
        1 (0, 1)                (0, 1)          (0, 2)          (0, 3)          (0, 4)
        2 (0, 1, 2)             (0, 1, 1)       (0, 1, 2)       (0, 2, 3)       (0, 2, 4)
        3 (0, 1, 2, 3)          (0, 0, 1, 1)    (0, 1, 1, 2)    (0, 1, 2, 3)    (0, 1, 3, 4)
        4 (0, 1, 2, 3, 4)       (0, 0, 1, 1, 1) (0, 1, 1, 2, 2) (0, 1, 2, 2, 3) (0, 1, 2, 3, 4)

        note that in printing heatmaps, all numbers will be converted to their 4-step equivalents.
"""

if len(sys.argv) == 1 or (len(sys.argv) == 2 and sys.argv[1] not in ["help", "steps"]):
    print(comms)
else:
    match sys.argv[1]:
        case "habit":
            match sys.argv[2]:
                case "-a" | "--add":
                    try:
                        main.add(dic, sys.argv[3])
                    except:
                        print("not enough arguments.")
                case "-r" | "--remove":
                    try:
                        try:
                            del dic[sys.argv[3]]
                        except:
                            print("not found")
                        else:
                            print(f"{sys.argv[3]} deleted.")
                    except:
                        print("not enough arguments.")
                case "-t" | "--track":
                    if len(sys.argv) == 4:
                        main.multitrack(dic, sys.argv[3])
                    elif len(sys.argv) == 6:
                        main.track(dic, *sys.argv[3:6])
                    else:
                        print("not enough arguments.")
                case _:
                    print("invalid command.")

        case "map":
            match sys.argv[2]:
                case "-l" | "--list":
                    for habit in dic:
                        print("    " + habit)
                case "-d" | "--day":
                    match len(sys.argv):
                        case 5:
                            main.daymap(*sys.argv[3:5], defcol[1:], dic, "day")
                        case 6:
                            main.daymap(*sys.argv[3:5], sys.argv[5][1:], dic, "day")
                        case _:
                            print("not enough arguments.")
                case "-m" | "--month":
                    match len(sys.argv):
                        case 5:
                            main.monthmap(*sys.argv[3:5], defcol[1:], dic)
                        case 6:
                            main.monthmap(*sys.argv[3:5], sys.argv[5][1:], dic)
                        case _:
                            print("not enough arguments.")
                case "-y" | "--year":
                    match len(sys.argv):
                        case 5:
                            main.yearmap(*sys.argv[3:5], defcol[1:], dic)
                        case 6:
                            main.yearmap(*sys.argv[3:5], sys.argv[5][1:])
                        case _:
                            print("not enough arguments.")
                case "-b" | "--bydur":
                    match len(sys.argv):
                        case 6:
                            main.daymap(*sys.argv[3:5], defcol[1:], dic, sys.argv[5])
                        case 7:
                            main.daymap(*sys.argv[3:5], sys.argv[6][1:], dic, sys.argv[5])
                case _:
                    print("invalid command.")
        case "help":
            print(help)
        case "steps":
            if len(sys.argv) == 3: 
                try:
                    new = int(sys.argv[2])
                    if new < 1 or new > 4:
                        raise TypeError
                except:
                    print("invalid number.")
                else:
                    dic["stepno"] = new
            else:
                print("not enough arguments.")
        case _:
            print("invalid command.")

td = dt.date.today()
open(os.getcwd()+"/stats.json", "w").write(json.dumps(dic, indent=4))
